/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cards;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;

public class Menu {
	
	public static void main(String[] args) {
		setGUI();	
    }
	
	public static void setGUI() {
		
		Deck deck = new Deck();
		
		//Set up Buttons.
		JFrame frame = new JFrame("Card Game");
		
		JButton btn1 = new JButton("Shuffle");
		btn1.setBounds(50,100,150,50);
		JButton btn2 = new JButton("Sort");
		btn2.setBounds(50,170,150,50);
		JButton btn3 = new JButton("Draw");
		btn3.setBounds(50,240,150,50);
		
		// Set up image
		Icon ic = new ImageIcon("Cards.Menu/resources/back.png");
		JButton btn4 = new JButton(ic);
		btn4.setBounds(220,100,250,350);
		
		frame.add(btn1); frame.add(btn2); frame.add(btn3); frame.add(btn4); 
		frame.setSize(600,600);
		frame.setLayout(null);
		frame.setVisible(true);
		
		//Event listeners
		btn1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Collections.shuffle(deck.cards);
			}
		});
		
		btn2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				deck.cards.clear();
				deck.setUpCards();
			}
		});
		
		btn3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					ImageIcon s1 = new ImageIcon (new ImageIcon("resources/" + deck.cards.get(0).getCard()
							+ ".png").getImage().getScaledInstance(260,380, Image.SCALE_SMOOTH));
					btn4.setIcon(s1);
					deck.cards.remove(0);
				}
				catch (Exception err) {
					System.out.println("Empty array..");
				}
			}
		});
	}
	
}
